In [1]:
import numpy as np

In [3]:
data=np.random.randint(0,100,size=20).reshape((4,5))
data

array([[51, 16, 98, 74, 72],
       [58, 67, 56, 52, 50],
       [24, 62, 38, 56,  2],
       [25,  3, 25,  0, 37]], dtype=int32)

In [4]:
data.ndim,data.shape,data.size,data.dtype

(2, (4, 5), 20, dtype('int32'))

In [5]:
data[0]

array([51, 16, 98, 74, 72], dtype=int32)

In [8]:
data[0:5:2,0:4:3]

array([[51, 74],
       [24, 56]], dtype=int32)

In [9]:
data[0,-5]

np.int32(51)

In [12]:
data.sum(),data.mean(),np.median(data),data.max(),data.min(),data.std(),data.argmax(),data.argmin()

(np.int64(866),
 np.float64(43.3),
 np.float64(50.5),
 np.int32(98),
 np.int32(0),
 np.float64(25.930869634472344),
 np.int64(2),
 np.int64(18))