In [35]:
import numpy as np
import pandas as pd

In [36]:
pristine_data=pd.read_csv("C:\\Users\\zakni\\Downloads\\kc_house_data.csv")
pristine_data

id             date     price  bedrooms  bathrooms  \
0      7129300520  20141013T000000  221900.0         3       1.00   
1      6414100192  20141209T000000  538000.0         3       2.25   
2      5631500400  20150225T000000  180000.0         2       1.00   
3      2487200875  20141209T000000  604000.0         4       3.00   
4      1954400510  20150218T000000  510000.0         3       2.00   
...           ...              ...       ...       ...        ...   
21608   263000018  20140521T000000  360000.0         3       2.50   
21609  6600060120  20150223T000000  400000.0         4       2.50   
21610  1523300141  20140623T000000  402101.0         2       0.75   
21611   291310100  20150116T000000  400000.0         3       2.50   
21612  1523300157  20141015T000000  325000.0         2       0.75   

       sqft_living  sqft_lot  floors  waterfront  view  ...  grade  \
0             1180      5650     1.0           0     0  ...      7   
1             2570      7242     2.0           0     0  ...      7   
2              770     10000     1.0           0     0  ...      6   
3             1960      5000     1.0           0     0  ...      7   
4             1680      8080     1.0           0     0  ...      8   
...            ...       ...     ...         ...   ...  ...    ...   
21608         1530      1131     3.0           0     0  ...      8   
21609         2310      5813     2.0           0     0  ...      8   
21610         1020      1350     2.0           0     0  ...      7   
21611         1600      2388     2.0           0     0  ...      8   
21612         1020      1076     2.0           0     0  ...      7   

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat  \
0            1180              0      1955             0    98178  47.5112   
1            2170            400      1951          1991    98125  47.7210   
2             770              0      1933             0    98028  47.7379   
3            1050            910      1965             0    98136  47.5208   
4            1680              0      1987             0    98074  47.6168   
...           ...            ...       ...           ...      ...      ...   
21608        1530              0      2009             0    98103  47.6993   
21609        2310              0      2014             0    98146  47.5107   
21610        1020              0      2009             0    98144  47.5944   
21611        1600              0      2004             0    98027  47.5345   
21612        1020              0      2008             0    98144  47.5941   

          long  sqft_living15  sqft_lot15  
0     -122.257           1340        5650  
1     -122.319           1690        7639  
2     -122.233           2720        8062  
3     -122.393           1360        5000  
4     -122.045           1800        7503  
...        ...            ...         ...  
21608 -122.346           1530        1509  
21609 -122.362           1830        7200  
21610 -122.299           1020        2007  
21611 -122.069           1410        1287  
21612 -122.299           1020        1357  

[21613 rows x 21 columns]

In [37]:
work_data1=pristine_data.copy(deep=True)
work_data1.loc[0,"bedrooms"]=4
work_data1.head(1)

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         4        1.0         1180   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   

   sqft_lot15  
0        5650  

[1 rows x 21 columns]

In [38]:
pristine_data.head(1)

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3        1.0         1180   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   

   sqft_lot15  
0        5650  

[1 rows x 21 columns]

In [39]:
len(pristine_data)

21613

In [40]:
print(pristine_data.shape[0])

21613


In [41]:
work_data1.set_index("id",inplace=True)
work_data1

date     price  bedrooms  bathrooms  sqft_living  \
id                                                                        
7129300520  20141013T000000  221900.0         4       1.00         1180   
6414100192  20141209T000000  538000.0         3       2.25         2570   
5631500400  20150225T000000  180000.0         2       1.00          770   
2487200875  20141209T000000  604000.0         4       3.00         1960   
1954400510  20150218T000000  510000.0         3       2.00         1680   
...                     ...       ...       ...        ...          ...   
263000018   20140521T000000  360000.0         3       2.50         1530   
6600060120  20150223T000000  400000.0         4       2.50         2310   
1523300141  20140623T000000  402101.0         2       0.75         1020   
291310100   20150116T000000  400000.0         3       2.50         1600   
1523300157  20141015T000000  325000.0         2       0.75         1020   

            sqft_lot  floors  waterfront  view  condition  grade  sqft_above  \
id                                                                             
7129300520      5650     1.0           0     0          3      7        1180   
6414100192      7242     2.0           0     0          3      7        2170   
5631500400     10000     1.0           0     0          3      6         770   
2487200875      5000     1.0           0     0          5      7        1050   
1954400510      8080     1.0           0     0          3      8        1680   
...              ...     ...         ...   ...        ...    ...         ...   
263000018       1131     3.0           0     0          3      8        1530   
6600060120      5813     2.0           0     0          3      8        2310   
1523300141      1350     2.0           0     0          3      7        1020   
291310100       2388     2.0           0     0          3      8        1600   
1523300157      1076     2.0           0     0          3      7        1020   

            sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
id                                                                             
7129300520              0      1955             0    98178  47.5112 -122.257   
6414100192            400      1951          1991    98125  47.7210 -122.319   
5631500400              0      1933             0    98028  47.7379 -122.233   
2487200875            910      1965             0    98136  47.5208 -122.393   
1954400510              0      1987             0    98074  47.6168 -122.045   
...                   ...       ...           ...      ...      ...      ...   
263000018               0      2009             0    98103  47.6993 -122.346   
6600060120              0      2014             0    98146  47.5107 -122.362   
1523300141              0      2009             0    98144  47.5944 -122.299   
291310100               0      2004             0    98027  47.5345 -122.069   
1523300157              0      2008             0    98144  47.5941 -122.299   

            sqft_living15  sqft_lot15  
id                                     
7129300520           1340        5650  
6414100192           1690        7639  
5631500400           2720        8062  
2487200875           1360        5000  
1954400510           1800        7503  
...                   ...         ...  
263000018            1530        1509  
6600060120           1830        7200  
1523300141           1020        2007  
291310100            1410        1287  
1523300157           1020        1357  

[21613 rows x 20 columns]

In [42]:
work_data1.nunique()

date              372
price            4028
bedrooms           13
bathrooms          30
sqft_living      1038
sqft_lot         9782
floors              6
waterfront          2
view                5
condition           5
grade              12
sqft_above        946
sqft_basement     306
yr_built          116
yr_renovated       70
zipcode            70
lat              5034
long              752
sqft_living15     777
sqft_lot15       8689
dtype: int64

In [43]:
work_data1.rename(columns={"bedrooms" : "Count_of_bedrooms"})

date     price  Count_of_bedrooms  bathrooms  \
id                                                                    
7129300520  20141013T000000  221900.0                  4       1.00   
6414100192  20141209T000000  538000.0                  3       2.25   
5631500400  20150225T000000  180000.0                  2       1.00   
2487200875  20141209T000000  604000.0                  4       3.00   
1954400510  20150218T000000  510000.0                  3       2.00   
...                     ...       ...                ...        ...   
263000018   20140521T000000  360000.0                  3       2.50   
6600060120  20150223T000000  400000.0                  4       2.50   
1523300141  20140623T000000  402101.0                  2       0.75   
291310100   20150116T000000  400000.0                  3       2.50   
1523300157  20141015T000000  325000.0                  2       0.75   

            sqft_living  sqft_lot  floors  waterfront  view  condition  grade  \
id                                                                              
7129300520         1180      5650     1.0           0     0          3      7   
6414100192         2570      7242     2.0           0     0          3      7   
5631500400          770     10000     1.0           0     0          3      6   
2487200875         1960      5000     1.0           0     0          5      7   
1954400510         1680      8080     1.0           0     0          3      8   
...                 ...       ...     ...         ...   ...        ...    ...   
263000018          1530      1131     3.0           0     0          3      8   
6600060120         2310      5813     2.0           0     0          3      8   
1523300141         1020      1350     2.0           0     0          3      7   
291310100          1600      2388     2.0           0     0          3      8   
1523300157         1020      1076     2.0           0     0          3      7   

            sqft_above  sqft_basement  yr_built  yr_renovated  zipcode  \
id                                                                       
7129300520        1180              0      1955             0    98178   
6414100192        2170            400      1951          1991    98125   
5631500400         770              0      1933             0    98028   
2487200875        1050            910      1965             0    98136   
1954400510        1680              0      1987             0    98074   
...                ...            ...       ...           ...      ...   
263000018         1530              0      2009             0    98103   
6600060120        2310              0      2014             0    98146   
1523300141        1020              0      2009             0    98144   
291310100         1600              0      2004             0    98027   
1523300157        1020              0      2008             0    98144   

                lat     long  sqft_living15  sqft_lot15  
id                                                       
7129300520  47.5112 -122.257           1340        5650  
6414100192  47.7210 -122.319           1690        7639  
5631500400  47.7379 -122.233           2720        8062  
2487200875  47.5208 -122.393           1360        5000  
1954400510  47.6168 -122.045           1800        7503  
...             ...      ...            ...         ...  
263000018   47.6993 -122.346           1530        1509  
6600060120  47.5107 -122.362           1830        7200  
1523300141  47.5944 -122.299           1020        2007  
291310100   47.5345 -122.069           1410        1287  
1523300157  47.5941 -122.299           1020        1357  

[21613 rows x 20 columns]

In [44]:
work_data1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 21613 entries, 7129300520 to 1523300157
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   date           21613 non-null  object 
 1   price          21613 non-null  float64
 2   bedrooms       21613 non-null  int64  
 3   bathrooms      21613 non-null  float64
 4   sqft_living    21613 non-null  int64  
 5   sqft_lot       21613 non-null  int64  
 6   floors         21613 non-null  float64
 7   waterfront     21613 non-null  int64  
 8   view           21613 non-null  int64  
 9   condition      21613 non-null  int64  
 10  grade          21613 non-null  int64  
 11  sqft_above     21613 non-null  int64  
 12  sqft_basement  21613 non-null  int64  
 13  yr_built       21613 non-null  int64  
 14  yr_renovated   21613 non-null  int64  
 15  zipcode        21613 non-null  int64  
 16  lat            21613 non-null  float64
 17  long           21613 non-null  float64
 1

In [45]:
work_data1.iloc[[2,3,7,8],2::3]=np.nan
work_data1

date     price  bedrooms  bathrooms  sqft_living  \
id                                                                        
7129300520  20141013T000000  221900.0       4.0       1.00         1180   
6414100192  20141209T000000  538000.0       3.0       2.25         2570   
5631500400  20150225T000000  180000.0       NaN       1.00          770   
2487200875  20141209T000000  604000.0       NaN       3.00         1960   
1954400510  20150218T000000  510000.0       3.0       2.00         1680   
...                     ...       ...       ...        ...          ...   
263000018   20140521T000000  360000.0       3.0       2.50         1530   
6600060120  20150223T000000  400000.0       4.0       2.50         2310   
1523300141  20140623T000000  402101.0       2.0       0.75         1020   
291310100   20150116T000000  400000.0       3.0       2.50         1600   
1523300157  20141015T000000  325000.0       2.0       0.75         1020   

            sqft_lot  floors  waterfront  view  condition  grade  sqft_above  \
id                                                                             
7129300520    5650.0     1.0           0   0.0          3      7      1180.0   
6414100192    7242.0     2.0           0   0.0          3      7      2170.0   
5631500400       NaN     1.0           0   NaN          3      6         NaN   
2487200875       NaN     1.0           0   NaN          5      7         NaN   
1954400510    8080.0     1.0           0   0.0          3      8      1680.0   
...              ...     ...         ...   ...        ...    ...         ...   
263000018     1131.0     3.0           0   0.0          3      8      1530.0   
6600060120    5813.0     2.0           0   0.0          3      8      2310.0   
1523300141    1350.0     2.0           0   0.0          3      7      1020.0   
291310100     2388.0     2.0           0   0.0          3      8      1600.0   
1523300157    1076.0     2.0           0   0.0          3      7      1020.0   

            sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
id                                                                             
7129300520              0      1955           0.0    98178  47.5112 -122.257   
6414100192            400      1951        1991.0    98125  47.7210 -122.319   
5631500400              0      1933           NaN    98028  47.7379      NaN   
2487200875            910      1965           NaN    98136  47.5208      NaN   
1954400510              0      1987           0.0    98074  47.6168 -122.045   
...                   ...       ...           ...      ...      ...      ...   
263000018               0      2009           0.0    98103  47.6993 -122.346   
6600060120              0      2014           0.0    98146  47.5107 -122.362   
1523300141              0      2009           0.0    98144  47.5944 -122.299   
291310100               0      2004           0.0    98027  47.5345 -122.069   
1523300157              0      2008           0.0    98144  47.5941 -122.299   

            sqft_living15  sqft_lot15  
id                                     
7129300520           1340        5650  
6414100192           1690        7639  
5631500400           2720        8062  
2487200875           1360        5000  
1954400510           1800        7503  
...                   ...         ...  
263000018            1530        1509  
6600060120           1830        7200  
1523300141           1020        2007  
291310100            1410        1287  
1523300157           1020        1357  

[21613 rows x 20 columns]

In [46]:
work_data1["Has_NaN"]=work_data1.isna().nunique(axis=1)
work_data1

date     price  bedrooms  bathrooms  sqft_living  \
id                                                                        
7129300520  20141013T000000  221900.0       4.0       1.00         1180   
6414100192  20141209T000000  538000.0       3.0       2.25         2570   
5631500400  20150225T000000  180000.0       NaN       1.00          770   
2487200875  20141209T000000  604000.0       NaN       3.00         1960   
1954400510  20150218T000000  510000.0       3.0       2.00         1680   
...                     ...       ...       ...        ...          ...   
263000018   20140521T000000  360000.0       3.0       2.50         1530   
6600060120  20150223T000000  400000.0       4.0       2.50         2310   
1523300141  20140623T000000  402101.0       2.0       0.75         1020   
291310100   20150116T000000  400000.0       3.0       2.50         1600   
1523300157  20141015T000000  325000.0       2.0       0.75         1020   

            sqft_lot  floors  waterfront  view  condition  ...  sqft_above  \
id                                                         ...               
7129300520    5650.0     1.0           0   0.0          3  ...      1180.0   
6414100192    7242.0     2.0           0   0.0          3  ...      2170.0   
5631500400       NaN     1.0           0   NaN          3  ...         NaN   
2487200875       NaN     1.0           0   NaN          5  ...         NaN   
1954400510    8080.0     1.0           0   0.0          3  ...      1680.0   
...              ...     ...         ...   ...        ...  ...         ...   
263000018     1131.0     3.0           0   0.0          3  ...      1530.0   
6600060120    5813.0     2.0           0   0.0          3  ...      2310.0   
1523300141    1350.0     2.0           0   0.0          3  ...      1020.0   
291310100     2388.0     2.0           0   0.0          3  ...      1600.0   
1523300157    1076.0     2.0           0   0.0          3  ...      1020.0   

            sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
id                                                                             
7129300520              0      1955           0.0    98178  47.5112 -122.257   
6414100192            400      1951        1991.0    98125  47.7210 -122.319   
5631500400              0      1933           NaN    98028  47.7379      NaN   
2487200875            910      1965           NaN    98136  47.5208      NaN   
1954400510              0      1987           0.0    98074  47.6168 -122.045   
...                   ...       ...           ...      ...      ...      ...   
263000018               0      2009           0.0    98103  47.6993 -122.346   
6600060120              0      2014           0.0    98146  47.5107 -122.362   
1523300141              0      2009           0.0    98144  47.5944 -122.299   
291310100               0      2004           0.0    98027  47.5345 -122.069   
1523300157              0      2008           0.0    98144  47.5941 -122.299   

            sqft_living15  sqft_lot15  Has_NaN  
id                                              
7129300520           1340        5650        1  
6414100192           1690        7639        1  
5631500400           2720        8062        2  
2487200875           1360        5000        2  
1954400510           1800        7503        1  
...                   ...         ...      ...  
263000018            1530        1509        1  
6600060120           1830        7200        1  
1523300141           1020        2007        1  
291310100            1410        1287        1  
1523300157           1020        1357        1  

[21613 rows x 21 columns]

In [47]:
work_data1.groupby("Has_NaN")["Has_NaN"].count()

Has_NaN
1    21609
2        4
Name: Has_NaN, dtype: int64

In [48]:
work_data1.dropna(inplace=True)
work_data1

date      price  bedrooms  bathrooms  sqft_living  \
id                                                                         
7129300520  20141013T000000   221900.0       4.0       1.00         1180   
6414100192  20141209T000000   538000.0       3.0       2.25         2570   
1954400510  20150218T000000   510000.0       3.0       2.00         1680   
7237550310  20140512T000000  1225000.0       4.0       4.50         5420   
1321400060  20140627T000000   257500.0       3.0       2.25         1715   
...                     ...        ...       ...        ...          ...   
263000018   20140521T000000   360000.0       3.0       2.50         1530   
6600060120  20150223T000000   400000.0       4.0       2.50         2310   
1523300141  20140623T000000   402101.0       2.0       0.75         1020   
291310100   20150116T000000   400000.0       3.0       2.50         1600   
1523300157  20141015T000000   325000.0       2.0       0.75         1020   

            sqft_lot  floors  waterfront  view  condition  ...  sqft_above  \
id                                                         ...               
7129300520    5650.0     1.0           0   0.0          3  ...      1180.0   
6414100192    7242.0     2.0           0   0.0          3  ...      2170.0   
1954400510    8080.0     1.0           0   0.0          3  ...      1680.0   
7237550310  101930.0     1.0           0   0.0          3  ...      3890.0   
1321400060    6819.0     2.0           0   0.0          3  ...      1715.0   
...              ...     ...         ...   ...        ...  ...         ...   
263000018     1131.0     3.0           0   0.0          3  ...      1530.0   
6600060120    5813.0     2.0           0   0.0          3  ...      2310.0   
1523300141    1350.0     2.0           0   0.0          3  ...      1020.0   
291310100     2388.0     2.0           0   0.0          3  ...      1600.0   
1523300157    1076.0     2.0           0   0.0          3  ...      1020.0   

            sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
id                                                                             
7129300520              0      1955           0.0    98178  47.5112 -122.257   
6414100192            400      1951        1991.0    98125  47.7210 -122.319   
1954400510              0      1987           0.0    98074  47.6168 -122.045   
7237550310           1530      2001           0.0    98053  47.6561 -122.005   
1321400060              0      1995           0.0    98003  47.3097 -122.327   
...                   ...       ...           ...      ...      ...      ...   
263000018               0      2009           0.0    98103  47.6993 -122.346   
6600060120              0      2014           0.0    98146  47.5107 -122.362   
1523300141              0      2009           0.0    98144  47.5944 -122.299   
291310100               0      2004           0.0    98027  47.5345 -122.069   
1523300157              0      2008           0.0    98144  47.5941 -122.299   

            sqft_living15  sqft_lot15  Has_NaN  
id                                              
7129300520           1340        5650        1  
6414100192           1690        7639        1  
1954400510           1800        7503        1  
7237550310           4760      101930        1  
1321400060           2238        6819        1  
...                   ...         ...      ...  
263000018            1530        1509        1  
6600060120           1830        7200        1  
1523300141           1020        2007        1  
291310100            1410        1287        1  
1523300157           1020        1357        1  

[21609 rows x 21 columns]

In [49]:
work_data1.iloc[:10:2,2::3]=np.nan
work_data1.head(10)

date      price  bedrooms  bathrooms  sqft_living  \
id                                                                         
7129300520  20141013T000000   221900.0       NaN       1.00         1180   
6414100192  20141209T000000   538000.0       3.0       2.25         2570   
1954400510  20150218T000000   510000.0       NaN       2.00         1680   
7237550310  20140512T000000  1225000.0       4.0       4.50         5420   
1321400060  20140627T000000   257500.0       NaN       2.25         1715   
3793500160  20150312T000000   323000.0       3.0       2.50         1890   
1736800520  20150403T000000   662500.0       NaN       2.50         3560   
9212900260  20140527T000000   468000.0       2.0       1.00         1160   
114101516   20140528T000000   310000.0       NaN       1.00         1430   
6054650070  20141007T000000   400000.0       3.0       1.75         1370   

            sqft_lot  floors  waterfront  view  condition  ...  sqft_above  \
id                                                         ...               
7129300520       NaN     1.0           0   NaN          3  ...         NaN   
6414100192    7242.0     2.0           0   0.0          3  ...      2170.0   
1954400510       NaN     1.0           0   NaN          3  ...         NaN   
7237550310  101930.0     1.0           0   0.0          3  ...      3890.0   
1321400060       NaN     2.0           0   NaN          3  ...         NaN   
3793500160    6560.0     2.0           0   0.0          3  ...      1890.0   
1736800520       NaN     1.0           0   NaN          3  ...         NaN   
9212900260    6000.0     1.0           0   0.0          4  ...       860.0   
114101516        NaN     1.5           0   NaN          4  ...         NaN   
6054650070    9680.0     1.0           0   0.0          4  ...      1370.0   

            sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
id                                                                             
7129300520              0      1955           NaN    98178  47.5112      NaN   
6414100192            400      1951        1991.0    98125  47.7210 -122.319   
1954400510              0      1987           NaN    98074  47.6168      NaN   
7237550310           1530      2001           0.0    98053  47.6561 -122.005   
1321400060              0      1995           NaN    98003  47.3097      NaN   
3793500160              0      2003           0.0    98038  47.3684 -122.031   
1736800520           1700      1965           NaN    98007  47.6007      NaN   
9212900260            300      1942           0.0    98115  47.6900 -122.292   
114101516               0      1927           NaN    98028  47.7558      NaN   
6054650070              0      1977           0.0    98074  47.6127 -122.045   

            sqft_living15  sqft_lot15  Has_NaN  
id                                              
7129300520           1340        5650      NaN  
6414100192           1690        7639      1.0  
1954400510           1800        7503      NaN  
7237550310           4760      101930      1.0  
1321400060           2238        6819      NaN  
3793500160           2390        7570      1.0  
1736800520           2210        8925      NaN  
9212900260           1330        6000      1.0  
114101516            1780       12697      NaN  
6054650070           1370       10208      1.0  

[10 rows x 21 columns]

In [50]:
work_data1["id"]=work_data1.index
work_data1.head()

date      price  bedrooms  bathrooms  sqft_living  \
id                                                                         
7129300520  20141013T000000   221900.0       NaN       1.00         1180   
6414100192  20141209T000000   538000.0       3.0       2.25         2570   
1954400510  20150218T000000   510000.0       NaN       2.00         1680   
7237550310  20140512T000000  1225000.0       4.0       4.50         5420   
1321400060  20140627T000000   257500.0       NaN       2.25         1715   

            sqft_lot  floors  waterfront  view  condition  ...  sqft_basement  \
id                                                         ...                  
7129300520       NaN     1.0           0   NaN          3  ...              0   
6414100192    7242.0     2.0           0   0.0          3  ...            400   
1954400510       NaN     1.0           0   NaN          3  ...              0   
7237550310  101930.0     1.0           0   0.0          3  ...           1530   
1321400060       NaN     2.0           0   NaN          3  ...              0   

            yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
id                                                                             
7129300520      1955           NaN    98178  47.5112      NaN           1340   
6414100192      1951        1991.0    98125  47.7210 -122.319           1690   
1954400510      1987           NaN    98074  47.6168      NaN           1800   
7237550310      2001           0.0    98053  47.6561 -122.005           4760   
1321400060      1995           NaN    98003  47.3097      NaN           2238   

            sqft_lot15  Has_NaN          id  
id                                           
7129300520        5650      NaN  7129300520  
6414100192        7639      1.0  6414100192  
1954400510        7503      NaN  1954400510  
7237550310      101930      1.0  7237550310  
1321400060        6819      NaN  1321400060  

[5 rows x 22 columns]

In [51]:
work_data1.index=range(len(work_data1))
work_data1.head()

date      price  bedrooms  bathrooms  sqft_living  sqft_lot  \
0  20141013T000000   221900.0       NaN       1.00         1180       NaN   
1  20141209T000000   538000.0       3.0       2.25         2570    7242.0   
2  20150218T000000   510000.0       NaN       2.00         1680       NaN   
3  20140512T000000  1225000.0       4.0       4.50         5420  101930.0   
4  20140627T000000   257500.0       NaN       2.25         1715       NaN   

   floors  waterfront  view  condition  ...  sqft_basement  yr_built  \
0     1.0           0   NaN          3  ...              0      1955   
1     2.0           0   0.0          3  ...            400      1951   
2     1.0           0   NaN          3  ...              0      1987   
3     1.0           0   0.0          3  ...           1530      2001   
4     2.0           0   NaN          3  ...              0      1995   

   yr_renovated  zipcode      lat     long  sqft_living15  sqft_lot15  \
0           NaN    98178  47.5112      NaN           1340        5650   
1        1991.0    98125  47.7210 -122.319           1690        7639   
2           NaN    98074  47.6168      NaN           1800        7503   
3           0.0    98053  47.6561 -122.005           4760      101930   
4           NaN    98003  47.3097      NaN           2238        6819   

   Has_NaN          id  
0      NaN  7129300520  
1      1.0  6414100192  
2      NaN  1954400510  
3      1.0  7237550310  
4      NaN  1321400060  

[5 rows x 22 columns]

In [52]:
work_data1.fillna(0,inplace=True)
work_data1

date      price  bedrooms  bathrooms  sqft_living  sqft_lot  \
0      20141013T000000   221900.0       0.0       1.00         1180       0.0   
1      20141209T000000   538000.0       3.0       2.25         2570    7242.0   
2      20150218T000000   510000.0       0.0       2.00         1680       0.0   
3      20140512T000000  1225000.0       4.0       4.50         5420  101930.0   
4      20140627T000000   257500.0       0.0       2.25         1715       0.0   
...                ...        ...       ...        ...          ...       ...   
21604  20140521T000000   360000.0       3.0       2.50         1530    1131.0   
21605  20150223T000000   400000.0       4.0       2.50         2310    5813.0   
21606  20140623T000000   402101.0       2.0       0.75         1020    1350.0   
21607  20150116T000000   400000.0       3.0       2.50         1600    2388.0   
21608  20141015T000000   325000.0       2.0       0.75         1020    1076.0   

       floors  waterfront  view  condition  ...  sqft_basement  yr_built  \
0         1.0           0   0.0          3  ...              0      1955   
1         2.0           0   0.0          3  ...            400      1951   
2         1.0           0   0.0          3  ...              0      1987   
3         1.0           0   0.0          3  ...           1530      2001   
4         2.0           0   0.0          3  ...              0      1995   
...       ...         ...   ...        ...  ...            ...       ...   
21604     3.0           0   0.0          3  ...              0      2009   
21605     2.0           0   0.0          3  ...              0      2014   
21606     2.0           0   0.0          3  ...              0      2009   
21607     2.0           0   0.0          3  ...              0      2004   
21608     2.0           0   0.0          3  ...              0      2008   

       yr_renovated  zipcode      lat     long  sqft_living15  sqft_lot15  \
0               0.0    98178  47.5112    0.000           1340        5650   
1            1991.0    98125  47.7210 -122.319           1690        7639   
2               0.0    98074  47.6168    0.000           1800        7503   
3               0.0    98053  47.6561 -122.005           4760      101930   
4               0.0    98003  47.3097    0.000           2238        6819   
...             ...      ...      ...      ...            ...         ...   
21604           0.0    98103  47.6993 -122.346           1530        1509   
21605           0.0    98146  47.5107 -122.362           1830        7200   
21606           0.0    98144  47.5944 -122.299           1020        2007   
21607           0.0    98027  47.5345 -122.069           1410        1287   
21608           0.0    98144  47.5941 -122.299           1020        1357   

       Has_NaN          id  
0          0.0  7129300520  
1          1.0  6414100192  
2          0.0  1954400510  
3          1.0  7237550310  
4          0.0  1321400060  
...        ...         ...  
21604      1.0   263000018  
21605      1.0  6600060120  
21606      1.0  1523300141  
21607      1.0   291310100  
21608      1.0  1523300157  

[21609 rows x 22 columns]

In [53]:
work_data1.drop(["Has_NaN"],axis=1)

date      price  bedrooms  bathrooms  sqft_living  sqft_lot  \
0      20141013T000000   221900.0       0.0       1.00         1180       0.0   
1      20141209T000000   538000.0       3.0       2.25         2570    7242.0   
2      20150218T000000   510000.0       0.0       2.00         1680       0.0   
3      20140512T000000  1225000.0       4.0       4.50         5420  101930.0   
4      20140627T000000   257500.0       0.0       2.25         1715       0.0   
...                ...        ...       ...        ...          ...       ...   
21604  20140521T000000   360000.0       3.0       2.50         1530    1131.0   
21605  20150223T000000   400000.0       4.0       2.50         2310    5813.0   
21606  20140623T000000   402101.0       2.0       0.75         1020    1350.0   
21607  20150116T000000   400000.0       3.0       2.50         1600    2388.0   
21608  20141015T000000   325000.0       2.0       0.75         1020    1076.0   

       floors  waterfront  view  condition  ...  sqft_above  sqft_basement  \
0         1.0           0   0.0          3  ...         0.0              0   
1         2.0           0   0.0          3  ...      2170.0            400   
2         1.0           0   0.0          3  ...         0.0              0   
3         1.0           0   0.0          3  ...      3890.0           1530   
4         2.0           0   0.0          3  ...         0.0              0   
...       ...         ...   ...        ...  ...         ...            ...   
21604     3.0           0   0.0          3  ...      1530.0              0   
21605     2.0           0   0.0          3  ...      2310.0              0   
21606     2.0           0   0.0          3  ...      1020.0              0   
21607     2.0           0   0.0          3  ...      1600.0              0   
21608     2.0           0   0.0          3  ...      1020.0              0   

       yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0          1955           0.0    98178  47.5112    0.000           1340   
1          1951        1991.0    98125  47.7210 -122.319           1690   
2          1987           0.0    98074  47.6168    0.000           1800   
3          2001           0.0    98053  47.6561 -122.005           4760   
4          1995           0.0    98003  47.3097    0.000           2238   
...         ...           ...      ...      ...      ...            ...   
21604      2009           0.0    98103  47.6993 -122.346           1530   
21605      2014           0.0    98146  47.5107 -122.362           1830   
21606      2009           0.0    98144  47.5944 -122.299           1020   
21607      2004           0.0    98027  47.5345 -122.069           1410   
21608      2008           0.0    98144  47.5941 -122.299           1020   

       sqft_lot15          id  
0            5650  7129300520  
1            7639  6414100192  
2            7503  1954400510  
3          101930  7237550310  
4            6819  1321400060  
...           ...         ...  
21604        1509   263000018  
21605        7200  6600060120  
21606        2007  1523300141  
21607        1287   291310100  
21608        1357  1523300157  

[21609 rows x 21 columns]

In [54]:
work_data1.iloc[:,1::1]

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  \
0       221900.0       0.0       1.00         1180       0.0     1.0   
1       538000.0       3.0       2.25         2570    7242.0     2.0   
2       510000.0       0.0       2.00         1680       0.0     1.0   
3      1225000.0       4.0       4.50         5420  101930.0     1.0   
4       257500.0       0.0       2.25         1715       0.0     2.0   
...          ...       ...        ...          ...       ...     ...   
21604   360000.0       3.0       2.50         1530    1131.0     3.0   
21605   400000.0       4.0       2.50         2310    5813.0     2.0   
21606   402101.0       2.0       0.75         1020    1350.0     2.0   
21607   400000.0       3.0       2.50         1600    2388.0     2.0   
21608   325000.0       2.0       0.75         1020    1076.0     2.0   

       waterfront  view  condition  grade  ...  sqft_basement  yr_built  \
0               0   0.0          3      7  ...              0      1955   
1               0   0.0          3      7  ...            400      1951   
2               0   0.0          3      8  ...              0      1987   
3               0   0.0          3     11  ...           1530      2001   
4               0   0.0          3      7  ...              0      1995   
...           ...   ...        ...    ...  ...            ...       ...   
21604           0   0.0          3      8  ...              0      2009   
21605           0   0.0          3      8  ...              0      2014   
21606           0   0.0          3      7  ...              0      2009   
21607           0   0.0          3      8  ...              0      2004   
21608           0   0.0          3      7  ...              0      2008   

       yr_renovated  zipcode      lat     long  sqft_living15  sqft_lot15  \
0               0.0    98178  47.5112    0.000           1340        5650   
1            1991.0    98125  47.7210 -122.319           1690        7639   
2               0.0    98074  47.6168    0.000           1800        7503   
3               0.0    98053  47.6561 -122.005           4760      101930   
4               0.0    98003  47.3097    0.000           2238        6819   
...             ...      ...      ...      ...            ...         ...   
21604           0.0    98103  47.6993 -122.346           1530        1509   
21605           0.0    98146  47.5107 -122.362           1830        7200   
21606           0.0    98144  47.5944 -122.299           1020        2007   
21607           0.0    98027  47.5345 -122.069           1410        1287   
21608           0.0    98144  47.5941 -122.299           1020        1357   

       Has_NaN          id  
0          0.0  7129300520  
1          1.0  6414100192  
2          0.0  1954400510  
3          1.0  7237550310  
4          0.0  1321400060  
...        ...         ...  
21604      1.0   263000018  
21605      1.0  6600060120  
21606      1.0  1523300141  
21607      1.0   291310100  
21608      1.0  1523300157  

[21609 rows x 21 columns]

In [55]:
a=work_data1.iloc[:,1::1].sum(axis=0)
a.columns="sum"
a.T

price            1.167162e+10
bedrooms         7.282700e+04
bathrooms        4.569975e+04
sqft_living      4.494730e+07
sqft_lot         3.264245e+08
floors           3.229250e+04
waterfront       1.630000e+02
view             5.064000e+03
condition        7.367400e+04
grade            1.654610e+05
sqft_above       3.864069e+07
sqft_basement    6.298745e+06
yr_built         4.259151e+07
yr_renovated     1.824186e+06
zipcode          2.119366e+09
lat              1.027725e+06
long            -2.640309e+06
sqft_living15    4.292785e+07
sqft_lot15       2.759337e+08
Has_NaN          2.160400e+04
id               9.898152e+13
dtype: float64

In [56]:
work_data1.loc[len(work_data1)]=a
work_data1

date         price  bedrooms  bathrooms  sqft_living  \
0      20141013T000000  2.219000e+05       0.0       1.00       1180.0   
1      20141209T000000  5.380000e+05       3.0       2.25       2570.0   
2      20150218T000000  5.100000e+05       0.0       2.00       1680.0   
3      20140512T000000  1.225000e+06       4.0       4.50       5420.0   
4      20140627T000000  2.575000e+05       0.0       2.25       1715.0   
...                ...           ...       ...        ...          ...   
21605  20150223T000000  4.000000e+05       4.0       2.50       2310.0   
21606  20140623T000000  4.021010e+05       2.0       0.75       1020.0   
21607  20150116T000000  4.000000e+05       3.0       2.50       1600.0   
21608  20141015T000000  3.250000e+05       2.0       0.75       1020.0   
21609              NaN  1.167162e+10   72827.0   45699.75   44947303.0   

          sqft_lot   floors  waterfront    view  condition  ...  \
0              0.0      1.0         0.0     0.0        3.0  ...   
1           7242.0      2.0         0.0     0.0        3.0  ...   
2              0.0      1.0         0.0     0.0        3.0  ...   
3         101930.0      1.0         0.0     0.0        3.0  ...   
4              0.0      2.0         0.0     0.0        3.0  ...   
...            ...      ...         ...     ...        ...  ...   
21605       5813.0      2.0         0.0     0.0        3.0  ...   
21606       1350.0      2.0         0.0     0.0        3.0  ...   
21607       2388.0      2.0         0.0     0.0        3.0  ...   
21608       1076.0      2.0         0.0     0.0        3.0  ...   
21609  326424463.0  32292.5       163.0  5064.0    73674.0  ...   

       sqft_basement    yr_built  yr_renovated       zipcode           lat  \
0                0.0      1955.0           0.0  9.817800e+04  4.751120e+01   
1              400.0      1951.0        1991.0  9.812500e+04  4.772100e+01   
2                0.0      1987.0           0.0  9.807400e+04  4.761680e+01   
3             1530.0      2001.0           0.0  9.805300e+04  4.765610e+01   
4                0.0      1995.0           0.0  9.800300e+04  4.730970e+01   
...              ...         ...           ...           ...           ...   
21605            0.0      2014.0           0.0  9.814600e+04  4.751070e+01   
21606            0.0      2009.0           0.0  9.814400e+04  4.759440e+01   
21607            0.0      2004.0           0.0  9.802700e+04  4.753450e+01   
21608            0.0      2008.0           0.0  9.814400e+04  4.759410e+01   
21609      6298745.0  42591513.0     1824186.0  2.119366e+09  1.027725e+06   

              long  sqft_living15   sqft_lot15  Has_NaN            id  
0            0.000         1340.0       5650.0      0.0  7.129301e+09  
1         -122.319         1690.0       7639.0      1.0  6.414100e+09  
2            0.000         1800.0       7503.0      0.0  1.954401e+09  
3         -122.005         4760.0     101930.0      1.0  7.237550e+09  
4            0.000         2238.0       6819.0      0.0  1.321400e+09  
...            ...            ...          ...      ...           ...  
21605     -122.362         1830.0       7200.0      1.0  6.600060e+09  
21606     -122.299         1020.0       2007.0      1.0  1.523300e+09  
21607     -122.069         1410.0       1287.0      1.0  2.913101e+08  
21608     -122.299         1020.0       1357.0      1.0  1.523300e+09  
21609 -2640308.662     42927849.0  275933746.0  21604.0  9.898152e+13  

[21610 rows x 22 columns]

In [57]:
work_data1.drop_duplicates(inplace=True)
work_data1


date         price  bedrooms  bathrooms  sqft_living  \
0      20141013T000000  2.219000e+05       0.0       1.00       1180.0   
1      20141209T000000  5.380000e+05       3.0       2.25       2570.0   
2      20150218T000000  5.100000e+05       0.0       2.00       1680.0   
3      20140512T000000  1.225000e+06       4.0       4.50       5420.0   
4      20140627T000000  2.575000e+05       0.0       2.25       1715.0   
...                ...           ...       ...        ...          ...   
21605  20150223T000000  4.000000e+05       4.0       2.50       2310.0   
21606  20140623T000000  4.021010e+05       2.0       0.75       1020.0   
21607  20150116T000000  4.000000e+05       3.0       2.50       1600.0   
21608  20141015T000000  3.250000e+05       2.0       0.75       1020.0   
21609              NaN  1.167162e+10   72827.0   45699.75   44947303.0   

          sqft_lot   floors  waterfront    view  condition  ...  \
0              0.0      1.0         0.0     0.0        3.0  ...   
1           7242.0      2.0         0.0     0.0        3.0  ...   
2              0.0      1.0         0.0     0.0        3.0  ...   
3         101930.0      1.0         0.0     0.0        3.0  ...   
4              0.0      2.0         0.0     0.0        3.0  ...   
...            ...      ...         ...     ...        ...  ...   
21605       5813.0      2.0         0.0     0.0        3.0  ...   
21606       1350.0      2.0         0.0     0.0        3.0  ...   
21607       2388.0      2.0         0.0     0.0        3.0  ...   
21608       1076.0      2.0         0.0     0.0        3.0  ...   
21609  326424463.0  32292.5       163.0  5064.0    73674.0  ...   

       sqft_basement    yr_built  yr_renovated       zipcode           lat  \
0                0.0      1955.0           0.0  9.817800e+04  4.751120e+01   
1              400.0      1951.0        1991.0  9.812500e+04  4.772100e+01   
2                0.0      1987.0           0.0  9.807400e+04  4.761680e+01   
3             1530.0      2001.0           0.0  9.805300e+04  4.765610e+01   
4                0.0      1995.0           0.0  9.800300e+04  4.730970e+01   
...              ...         ...           ...           ...           ...   
21605            0.0      2014.0           0.0  9.814600e+04  4.751070e+01   
21606            0.0      2009.0           0.0  9.814400e+04  4.759440e+01   
21607            0.0      2004.0           0.0  9.802700e+04  4.753450e+01   
21608            0.0      2008.0           0.0  9.814400e+04  4.759410e+01   
21609      6298745.0  42591513.0     1824186.0  2.119366e+09  1.027725e+06   

              long  sqft_living15   sqft_lot15  Has_NaN            id  
0            0.000         1340.0       5650.0      0.0  7.129301e+09  
1         -122.319         1690.0       7639.0      1.0  6.414100e+09  
2            0.000         1800.0       7503.0      0.0  1.954401e+09  
3         -122.005         4760.0     101930.0      1.0  7.237550e+09  
4            0.000         2238.0       6819.0      0.0  1.321400e+09  
...            ...            ...          ...      ...           ...  
21605     -122.362         1830.0       7200.0      1.0  6.600060e+09  
21606     -122.299         1020.0       2007.0      1.0  1.523300e+09  
21607     -122.069         1410.0       1287.0      1.0  2.913101e+08  
21608     -122.299         1020.0       1357.0      1.0  1.523300e+09  
21609 -2640308.662     42927849.0  275933746.0  21604.0  9.898152e+13  

[21610 rows x 22 columns]

In [58]:
b=work_data1.isin([0])

In [ ]:
work_data1[b]="Zero"
work_data1

In [ ]:
work_data1.groupby("bedrooms").agg({"bathrooms":"mean","price":"sum"}).reset_index()

In [ ]:
df = pd.DataFrame([[1,'Bob', 8000,10],
                  [2,'Sally', 9000,40],
                  [3,'Scott', 20,37]], columns=['id','name', 'power level1','power'])
df

In [ ]:
df1 = pd.DataFrame([[1,'Bobison', 300,15],
                  [4,'Gallyerry', 50,32],
                  [5,'Potter', 435,21]], columns=['id','Surname', 'power level2','power'])
df1

In [ ]:
df2=pd.concat([df,df1],axis=0,ignore_index=True)
df2

In [ ]:
df3=pd.concat([df,df1],axis=1)
df3

In [ ]:
df.merge(df1,how="outer",on="id",suffixes=["_left","_right"])

In [ ]:
df.merge(df1,how="inner",on="id",suffixes=["_left","_right"])

In [ ]:
df.merge(df1,how="left",on="id",suffixes=["_left","_right"])

In [ ]:
df.columns=['Id','name', 'power level1','power']
df.merge(df1,how="outer",left_on="Id",right_on="id",suffixes=["_left","_right"])

In [ ]:
work_data1.pivot_table(values="price",index=["bedrooms","bathrooms"],columns=["floors","long"],aggfunc="sum",fill_value=0).head(10)

In [ ]:
work_data1.sort_values("price",ascending=False)

In [ ]:
work_data1.dropna(inplace=True)
work_data1

In [ ]:
for idx,row in work_data1.iterrows():
    if(row.bathrooms==0):
        print(idx,"Good")

In [ ]:
work_data1.sample(frac=0.01)

In [ ]:
import numpy as np
x=np.array([[ 4,  3,  -5],
 [ 1, -2, -5],
 [ 5,  -3, 1]])
l1=list()
p=0
c=0
for t in range(1,3):
    if(p==1):
        break
    for i in range(-t,t+1):
        if(p==1):
            break
        for j in range(-t,t+1):
            if(p==1):
               break
            for k in range(-t,t+1):
                if(p==1):
                   break
                for i1 in range(-t,t+1):
                    if(p==1):
                       break
                    for j1 in range(-t,t+1):
                        if(p==1):
                            break
                        for k1 in range(-t,t+1):
                            if(p==1):
                                break
                            for i2 in range(-t,t+1):
                                if(p==1):
                                    break
                                for j2 in range(-t,t+1):
                                    if(p==1):
                                        break
                                    for k2 in range(-t,t+1):
                                        n=np.array([i*x[0,:]+j*x[1,:]+k*x[2,:],i1*x[0,:]+j1*x[1,:]+k1*x[2,:],i2*x[0,:]+j2*x[1,:]+k2*x[2,:]])
                                        if((np.abs(2*n[0,0])>np.sum(np.abs(n[0,:]))) & (np.abs(2*n[0,0])>np.sum(np.abs(n[:,0]))) & (np.abs(2*n[1,1])>np.sum(np.abs(n[1,:]))) & (np.abs(2*n[1,1])>np.sum(np.abs(n[:,1]))) & (np.abs(2*n[2,2])>np.sum(np.abs(n[2,:]))) & (np.abs(2*n[2,2])>np.sum(np.abs(n[:,2])))):
                                            #print(n)
                                            #print(i,j,k,i1,j1,k1,i2,j2,k2)
                                            #print(" ")
                                            l1.append((n,[i,j,k,i1,j1,k1,i2,j2,k2]))
                                            c+=1
                                            break
print(c)                                        
#print(l1)

x=np.array([[ 3,  -5,  1],
 [ -2, -5, 1],
 [ -3,  1, -4]])
l2=list()
p=0
c=0
for t in range(1,3):
    if(p==1):
        break
    for i in range(-t,t+1):
        if(p==1):
            break
        for j in range(-t,t+1):
            if(p==1):
               break
            for k in range(-t,t+1):
                if(p==1):
                   break
                for i1 in range(-t,t+1):
                    if(p==1):
                       break
                    for j1 in range(-t,t+1):
                        if(p==1):
                            break
                        for k1 in range(-t,t+1):
                            if(p==1):
                                break
                            for i2 in range(-t,t+1):
                                if(p==1):
                                    break
                                for j2 in range(-t,t+1):
                                    if(p==1):
                                        break
                                    for k2 in range(-t,t+1):
                                        n=np.array([i*x[0,:]+j*x[1,:]+k*x[2,:],i1*x[0,:]+j1*x[1,:]+k1*x[2,:],i2*x[0,:]+j2*x[1,:]+k2*x[2,:]])
                                        if((np.abs(2*n[0,0])>np.sum(np.abs(n[0,:]))) & (np.abs(2*n[0,0])>np.sum(np.abs(n[:,0]))) & (np.abs(2*n[1,1])>np.sum(np.abs(n[1,:]))) & (np.abs(2*n[1,1])>np.sum(np.abs(n[:,1]))) & (np.abs(2*n[2,2])>np.sum(np.abs(n[2,:]))) & (np.abs(2*n[2,2])>np.sum(np.abs(n[:,2])))):
                                            #print(n)
                                            #print(i,j,k,i1,j1,k1,i2,j2,k2)
                                            #print(" ")
                                            l2.append((n,[i,j,k,i1,j1,k1,i2,j2,k2]))
                                            c+=1
                                            break
print(c)                                        
#print(l2)
# & (p1[4:6]==p2[0:2]) & (p1[7:9]==p2[3:5])
for i in range(0,len(l1)):
    n1,p1=l1[i]
    for j in range(0, len(l2)):
        n2,p2=l2[j]
        if(np.allclose(n1[0:3,1:3],n2[0:3,0:2])):
            print(" --- ")
            print(l1[i])
            print(" ")
            print(l2[j])
            print(" --- ")

In [ ]:
for i in range(0,len(l1)):
    n1,p1=l1[i]
    print(n1)
    print(n1[0:3,1:3])
    for j in range(0, len(l2)):
        n2,p2=l2[j]
        if(np.allclose(n1[0:3,1:3],n2[0:3,0:2])):
            print(" --- ")
            print(l1[i])
            print(" ")
            print(l2[j])
            print(" --- ")

In [ ]:
import numpy as np
x=np.array([[ 3.77,  0.04,  0.21,  0.18],
 [ 2.74, -0.34, -0.11,  0.  ],
 [ 4.59,  0.23, -0.06,  0.  ],
 [ 0.95,  0.26, -0.36,  0.12]])
p=0
c=0
l=0
m=0
for t in range(1,2):
    print(t)
    if(p==1):
        break
    for i in [2,1]:
        if(p==1):
            break
        for j in [2,1]:
            if(p==1):
               break
            for k in [2,1]:
                if(p==1):
                   break
                for n in [2,1]:
                    if((i,j,k,n)==(0,0,0,0)):
                         break
                    if(p==1):
                       break
                    for i1 in [2,1]:
                        if(p==1):
                           break
                        for j1 in [2,1]:
                            if(p==1):
                               break
                            for k1 in [2,1]:
                                if(p==1):
                                    break
                                for n1 in [2,1]:
                                    if((i1,j1,k1,n1)==(0,0,0,0)):
                                         break
                                    if(p==1):
                                       break
                                    for i2 in [2,1]:
                                        if(p==1):
                                           break
                                        for j2 in [2,1]:
                                            if(p==1):
                                                break
                                            for k2 in [2,1]:
                                                if(p==1):
                                                    break
                                                for n2 in [2,1]:
                                                    if((i2,j2,k2,n2)==(0,0,0,0)):
                                                         break
                                                    if(sum(abs(np.array([i,j,k,n,i1,j1,k1,n1,i2,j2,k2,n2])))<3):
                                                                        continue

                                                    if(p==1):
                                                       break
                                                    for i3 in [2,1]:
                                                        if(sum(abs(np.array([i,j,k,n,i1,j1,k1,n1,i2,j2,k2,n2,i3])))<4):
                                                                        continue

                                                        if(p==1):
                                                            break
                                                        for j3 in [2,1]:
                                                            if(sum(abs(np.array([i,j,k,n,i1,j1,k1,n1,i2,j2,k2,n2,i3,j3])))<5):
                                                                        continue

                                                            if(p==1):
                                                                break
                                                            for k3 in [2,1]:
                                                                if(sum(abs(np.array([i,j,k,n,i1,j1,k1,n1,i2,j2,k2,n2,i3,j3,k3])))<6):
                                                                        continue
                                                                     
                                                                if(p==1):
                                                                   break
                                                                for n3 in [2,1]:
                                                                    if((i3,j3,k3,n3)==(0,0,0,0)):
                                                                         break
                                                                    if(sum(abs(np.array([i,j,k,n,i1,j1,k1,n1,i2,j2,k2,n2,i3,j3,k3,n3])))<7):
                                                                        continue
                                                                    nn=np.array([i*x[0,:]+j*x[1,:]+k*x[2,:]+n*x[3,:],i1*x[0,:]+j1*x[1,:]+k1*x[2,:]+n1*x[3,:],i2*x[0,:]+j2*x[1,:]+k2*x[2,:]+n2*x[3,:],i3*x[0,:]+j3*x[1,:]+k3*x[2,:]+n3*x[3,:]])
                                                                    if((np.abs(2*nn[0,0])>np.sum(np.abs(nn[0,:]))) & (np.abs(2*nn[0,0])>np.sum(np.abs(nn[:,0]))) & (np.abs(2*nn[1,1])>np.sum(np.abs(nn[1,:]))) & (np.abs(2*nn[1,1])>np.sum(np.abs(nn[:,1]))) & (np.abs(2*nn[2,2])>np.sum(np.abs(nn[2,:]))) & (np.abs(2*nn[2,2])>np.sum(np.abs(nn[:,2]))) & (np.abs(2*nn[3,3])>np.sum(np.abs(nn[3,:]))) & (np.abs(2*nn[3,3])>np.sum(np.abs(nn[:,3])))):
                                                                        print(nn)
                                                                        print(i,j,k,n,i1,j1,k1,n1,i2,j2,k2,n2,i3,j3,k3,n3)
                                                                        print(" ")
                                                                        p=1
                                                                        c+=1
                                                                        break
                                                                    l+=1
                                                                    print(l)
print(c)                         

In [ ]:
x=np.array([[ 5. ,  0.2 ,-0.7 , 1. ],
 [-1.,  -3.8 , 1.5,  1. ],
 [ 2.,   3.,  -8.4 , 0. ]])
print(f"({x[0,0]})*x1+({x[0,1]})*x2+({x[0,2]})*x3,({x[1,0]})*x1+({x[1,1]})*x2+({x[1,2]})*x3,({x[2,0]})*x1+({x[2,1]})*x2+({x[2,2]})*x3  {x[0,3]},{x[1,3]},{x[2,3]}")

In [ ]:
#4.12 , -3.621,  5.695, -2.403
x=np.array([[-1.00000000e+00, -2.73684211e-01,  3.78947368e-01,
        -1.26315789e-01, -1.02105263e-01],
       [ 5.12820513e-02,  1.00000000e+00, -1.70940171e-01,
         1.02564103e-01,  7.56743590e+01],
       [ 6.49350649e-02, -6.49350649e-02, -1.00000000e+00,
         3.11688312e-01, -1.18866234e+02],
       [ 8.07083333e-01,  5.20833333e-02,  8.66666667e-02,
         1.00000000e+00, -4.48728750e+01]])
i,j=x.shape
k=0

while(k<i):
    x[k,:]=x[k,:]/np.abs(x[k,k])
    k1=0
    while(k1<i):
        if(k==k1):
            k1+=1
            continue
        x[k1,:]=x[k1,:]-x[k,:]*(x[k1,k]/x[k,k])
        k1+=1
    k+=1    
print(x)

In [40]:
x=np.array([[-1.        , -0.01061008, -0.05570292, -0.04774536, -1.0928382 ],
       [-0.09774436,  1.        , -0.04135338,  0.        , -1.3612782 ],
       [ 0.08299595, -0.0465587 , -1.        ,  0.        , -1.15283401],
       [ 0.04464286, -0.23214286,  0.32142857, -1.        ,  2.14553571]])
i,j=x.shape
k=0

str=""
while(k<i):
    k1=0
    while(k1<j-1):
        str+=f"({x[k,k1]})*x{k1+1}"
        if(k1!=j-2):
            str+="+"
        k1+=1
    if(k!=i-1):
        str+=","
    k+=1
print(str)
print(x[:,j-1])

(-1.0)*x1+(-0.01061008)*x2+(-0.05570292)*x3+(-0.04774536)*x4,(-0.09774436)*x1+(1.0)*x2+(-0.04135338)*x3+(0.0)*x4,(0.08299595)*x1+(-0.0465587)*x2+(-1.0)*x3+(0.0)*x4,(0.04464286)*x1+(-0.23214286)*x2+(0.32142857)*x3+(-1.0)*x4
[-1.0928382  -1.3612782  -1.15283401  2.14553571]


In [41]:
import numpy as np
x=np.array([[ 4,  3,  -5,  1,-17],
 [ 1, -2, -5,  1 , -13 ],
 [ 5,  -3, 1,  -4 , 35 ],
 [ 10,  2, -1,  2, 5]])
i,j=x.shape
k=0

while(k<i):
    x[k,:]=x[k,:]/np.abs(x[k,k])
    k1=0
    while(k1<i):
        if(k==k1):
            k1+=1
            continue
        x[k1,:]=x[k1,:]-x[k,:]*(x[k1,k]/x[k,k])
        k1+=1
    k+=1    
print(x)        
    

[[ 1  0  0  0  1]
 [ 0 -1  0  0  6]
 [ 0  0  1  0  5]
 [ 0  0  0  1  6]]


In [39]:
import numpy as np
#[-1.        , -0.01061008, -0.05570292, -0.04774536, -1.0928382 ],
#       [-0.09774436,  1.        , -0.04135338,  0.        , -1.3612782 ],
#       [ 0.08299595, -0.0465587 , -1.        ,  0.        , -1.15283401],
#   c   [ 0.04464286, -0.23214286,  0.32142857, -1.        ,  2.14553571]
A=np.array([[ -1., -0.01061008, -0.05570292, -0.04774536],
 [ -0.09774436,  1.        , -0.04135338,  0.  ],
 [ 0.08299595, -0.0465587 , -1.        ,  0.],
 [ 0.04464286, -0.23214286,  0.32142857, -1.]])
B=np.array([4.12,3.279,4.695,0.097])
np.linalg.solve(A,B)
B=np.array([1.1,-1.2,1.3,-1.4])
B=np.dot(A,B)
A,B,np.linalg.det(A)
#np.linalg.solve(A,B)

(array([[-1.        , -0.01061008, -0.05570292, -0.04774536],
        [-0.09774436,  1.        , -0.04135338,  0.        ],
        [ 0.08299595, -0.0465587 , -1.        ,  0.        ],
        [ 0.04464286, -0.23214286,  0.32142857, -1.        ]]),
 array([-1.0928382 , -1.36127819, -1.15283402,  2.14553572]),
 np.float64(-1.0095865255096743))

In [ ]:
A=np.array([[ 3.77,  0.04,  0.21,  0.18],
 [ 2.74, -0.34, -0.11,  0.  ],
 [ 4.59,  0.23, -0.06,  0.  ],
 [ 0.95,  0.26, -0.36,  0.12]])
B=np.array([[ 3.77,  0.04,  0.21,  0.18],
 [ 2.74, -0.34, -0.11,  0.  ],
 [ 4.59,  0.23, -0.06,  0.  ],
 [ 0.95,  0.26, -0.36,  0.12]])
B[0,:]=A[0,:]+A[2,:]
B[1,:]=A[1,:]-A[3,:]*2
B[2,:]=A[2,:]-A[0,:]*1.5+2*A[3,:]
B[3,:]=A[3,:]*2
print(B)

In [ ]:
x=np.array([[ 4,  3,  -5,  1,-17],
 [ 1, -2, -5,  1 ,-13 ],
 [ 5,  -3, 1,  -4 ,35 ],
 [ 10,  2, -1,  2,5]])
g=x[:,4]
D=np.array([[ 0,  0,  0,  0],
 [ 1, 0, 0,  0  ],
 [ 5,  -3, 0,  0  ],
 [ 10,  2, -1,  0]])
L=np.array([[ 4,  0,  0,  0],
 [ 0, -2, 0,  0],
 [ 0,  0, 1,  0 ],
 [ 0,  0, 0,  2]])
U=np.array([[ 0,  3,  -5,  1],
 [ 0, 0, -5,  1 ],
 [ 0,  0, 0,  -4  ],
 [ 0,  0, 0,  0]])

-np.linalg.inv(D)

In [ ]:
import numpy as np
#4.12  3.279 4.695 0.097
e=0.001
X=np.array([[ 3.77,  0.04,  0.21,  0.18,4.12],
 [ 2.74, -0.34, -0.11,  0., 3.279  ],
 [ 4.59,  0.23, -0.06,  0., 4.695  ],
 [ 0.95,  0.26, -0.36,  0.12, 0.097]])
i,j=x.shape
A=X[:,0:j-1]
B=X[:,j-1]
A,B,type(range(0,4))


In [ ]:
import numpy as np

# Нормализация матрицы (главная диагональ обнуляется, остальные элементы делятся на диагональный элемент)
def normalize_matrix(A):
    n = A.shape[0]
    A_norm = np.zeros_like(A)
    
    for i in range(n):
        diag = A[i, i]
        if diag == 0:
            raise ValueError(f"Элемент диагонали равен нулю в строке {i+1}, нормализация невозможна.")
        A_norm[i] = A[i] / diag
        A_norm[i, i] = 0  # Диагональные элементы обнуляем
    
    return A_norm

# Проверка условий сходимости
def check_convergence_conditions_normalized(A):
    # Нормализация матрицы
    A_norm = normalize_matrix(A)
    
    # Условие 1: alpha = max(sum(|a_ij_norm|, j != i)) для строк
    alpha = max(np.sum(np.abs(A_norm), axis=1))  # Сумма по строкам, исключая диагональные элементы (они уже равны 0)
    
    # Условие 2: beta = max(sum(|a_ij_norm|, i != j)) для столбцов
    beta = max(np.sum(np.abs(A_norm), axis=0))  # Сумма по столбцам, исключая диагональные элементы (они уже равны 0)
    
    # Условие 3: gamma = sum((a_ij_norm)^2) — сумма квадратов всех нормализованных элементов
    gamma = np.sum(A_norm**2)  # Сумма квадратов всех элементов нормализованной матрицы (диагональ уже нули)
    
    return alpha, beta, gamma

# Метод простой итерации для решения СЛАУ
def simple_iteration(A, b, epsilon, max_iter=1000, x0=None):
    n = A.shape[0]
    
    # Проверка условий сходимости
    alpha, beta, gamma = check_convergence_conditions_normalized(A)
    print(f"Проверка условий сходимости:")
    print(f"alpha = {alpha} (должно быть < 1)")
    print(f"beta = {beta} (должно быть < 1)")
    print(f"gamma = {gamma} (должно быть < 1)")
    
    if alpha >= 1 or beta >= 1:
        print("Предупреждение: Условия сходимости могут не выполняться!")
    
    # Инициализация начального приближения
    if x0 is None:
        x = np.zeros(n)  # Если начальное приближение не задано, используем вектор нулей
    else:
        x = np.array(x0, dtype=float)

    # Итерационный процесс
    A_norm = normalize_matrix(A)
    b_norm = b / np.diag(A)
    
    print("\nНачало итераций:")
    for k in range(1, max_iter + 1):
        x_new = np.copy(b_norm)
        for i in range(n):
            x_new[i] -= np.dot(A_norm[i], x)  # Формула итерации

        # Рассчитываем максимальную погрешность
        error = np.max(np.abs(x_new - x))

        # Вывод промежуточных результатов
        print(f"Итерация {k}: x = {x_new}, Погрешность = {error}")

        # Проверка на сходимость
        if error <= epsilon:
            print(f"\nПроцесс сошелся на итерации {k}.")
            return x_new
        
        x = x_new  # Обновление вектора для следующей итерации

    print(f"\nМетод не сошелся за {max_iter} итераций.")
    return x

# Ввод матриц с диагональным преоблоданием, свободных членов, и эпсилон
A = np.array([[5, 0.2, -0.7],
              [1, 3.8, -1.5],
              [1, -1, 7.3]], dtype=float)

b = np.array([1, -1, 0], dtype=float)
epsilon = 1e-5


x0 = [0, 0, 0]  # Начальное приближение

# Запуск метода простой итерации
solution = simple_iteration(A, b, epsilon, x0=x0)
print(f"\nРешение при эпсилон {epsilon}: {solution}")


In [ ]:
import numpy as np

def inner_for(mas,zn,rez,fun,A,num=0):
    nez=rez
    if((type(num)!=int)|(num>len(mas))|(num<0)):
        print(f"Параметр num={num} не подходит")
        return None
    
    if(type(mas)!=np.ndarray):
        print(f"В функцию передали {mas} , а ожидался numpy.ndarray")
        return None
    
    for i in zn:

        mas[num]=i

        if(num==len(mas)-1):
            rez=fun(mas,rez,A)
        else:
            rez=inner_for(mas,zn,rez,fun,A,num+1)

        if(nez!=rez):
            if(num==0):
                i=zn[0]
            else:
                break    

        if(rez==len(A)):
            print(rez)
            print(len(A))
            break

    return rez

def fun(mas,rez,A):
    print(1)
    n=len(mas)
    d=np.zeros(n,dtype='float64')
    N=np.zeros_like(A,dtype='float64')
    stp=0

    for i in range(0,n):
        for j in range(0,n):
            d[i]+=mas[j]*A[j,i]
        d[i]=np.abs(d[i])

    for i in range(0,n):
        summ=d[i]
        for j in range(0,n):
            if(i!=j):
                summ-=d[j]
        print(summ)        
        if((i==rez) & (summ>0)):
            print(" ")
            print(rez)
            print(A)
            print(mas)
            rez+=1
            for k in range(0,n):
                N[i,:]+=A[k,:]*mas[k]
            A[i,:]=N[i,:]   
            print(A) 
            print(" ")
            stp=1
            break
        if(stp==1):break
    
    return rez

def diag_preobl(x,p=3):

    zn=range(0,p+1)

    if(type(x)!=np.ndarray):
        print(f"В функцию передали {x} , а ожидался numpy.ndarray")
        return None
    
    i,j=x.shape

    if((i<=1) | (j<=1) | (i!=j-1)):
        print(f"Размерности {x} не корректны")
        return None
    
    rez=0
    koef=np.zeros(j-1,dtype='float64')
    A=x[:,:]

    rez=inner_for(koef,zn,rez,fun,A)
                  

    return A

print(diag_preobl(np.array([[ 4,  3,  -5,  1,-17],
 [ 1, -2, -5,  1 ,-13 ],
 [ 5,  -3, 1,  -4 ,35 ],
 [ 10,  2, -1,  2,5]],dtype='float64'),10))

In [ ]:
rezult=list()

    for t in range(len(rez)):
        temp=list()
        temp.append(rez[t])

        for t1 in range(len(rez)):
            if(t1==t):
                continue
            if(len(temp)==i):
                break

            add=True
            for t2 in range(len(temp)):
                if(np.array_equal(temp[t2][1],rez[t1][1])):
                    add=False
            if(add):
                temp.append(rez[t1])

        a=np.zeros_like(x)
        for t1 in range(len(temp)):
            for t2 in range(len(temp)):
                if(temp[t1][1][t2]!=0):
                    for t3 in range(len(temp[t1][0])):
                        a[t2,:]=a[t2,:]+x[t3,:]*temp[t1][0][t3]

        add=True
        c=0
        for t1 in range(len(a)):
            if((2*np.abs(a[t1,t1])<np.sum(np.abs(a[t1,:])))&(2*np.abs(a[t1,t1])<np.sum(np.abs(a[:,t1])))):
                add=False
            else:
                c+=1
        if(c>2):
            print(a)

        if(add):
            rezult.append((a,temp))

In [2]:
import numpy as np

In [34]:
X=np.array([[ 3.77,  0.04,  0.21,  0.18,4.12],
        [-0.26,  2.66, -0.11,  0., -3.621 ],
        [-0.41,  0.23,  4.94,  0., 5.695 ],
        [-0.05,  0.26, -0.36,  1.12, -2.403]],dtype='float64')
print(X)
p=1
l=list()
l0=list()
l1=list()
l2=list()
l3=list()
for k in range(0,4):
    for A in range(-p,p+1):
        for B in range(-p,p+1):
            for C in range(-p,p+1):
                for D in range(-p,p+1):
                    d0=abs(A*X[0,0]+B*X[1,0]+C*X[2,0]+D*X[3,0])
                    d1=abs(A*X[0,1]+B*X[1,1]+C*X[2,1]+D*X[3,1])
                    d2=abs(A*X[0,2]+B*X[1,2]+C*X[2,2]+D*X[3,2])
                    d3=abs(A*X[0,3]+B*X[1,3]+C*X[2,3]+D*X[3,3])
                    
                    if((k==0)&(d0-d1-d2-d3>0)):
                        l0.append([A,B,C,D])
                    elif((k==1)&(d1-d0-d2-d3>0)):
                        l1.append([A,B,C,D])
                    elif((k==2)&(d2-d1-d0-d3>0)):
                        l2.append([A,B,C,D])
                    elif((k==3)&(d3-d1-d2-d0>0)):
                        l3.append([A,B,C,D])
print(len(l0),len(l1),len(l2),len(l3))
u=np.array([len(l0),len(l1),len(l2),len(l3)])
print(np.min(u))


[[ 3.77   0.04   0.21   0.18   4.12 ]
 [-0.26   2.66  -0.11   0.    -3.621]
 [-0.41   0.23   4.94   0.     5.695]
 [-0.05   0.26  -0.36   1.12  -2.403]]
12 6 22 2
2


In [36]:
num=0
t=len(l0)/2-10
t1=len(l1)/2-10
t2=len(l2)/2-10
t3=0#len(l3)/2
for i in l0:
    num+=1
    if(num<t):
        continue
    if(num>t+20):
        break
    num1=0
    for j in l1:
        num1+=1
        if(num1<t1):
          continue
        if(num1>t1+20):
          break
        num2=0
        for k in l2:
            num2+=1
            if(num2<t2):
              continue
            if(num2>t2+20):
              break
            num3=0
            for n in l3:
                num3+=1
                if(num3<t3):
                  continue
                if(num3>t3+20):
                  break
                N=np.zeros_like(X,dtype='float64')
                for s in range(0,4):
                    N[0,:]=N[0,:]+X[s,:]*i[s]
                    N[1,:]=N[1,:]+X[s,:]*j[s]
                    N[2,:]=N[2,:]+X[s,:]*k[s]
                    N[3,:]=N[3,:]+X[s,:]*n[s]
                N[0,:]=N[0,:]/np.max(np.abs(N[0,:4]))
                N[1,:]=N[1,:]/np.max(np.abs(N[1,:4]))
                N[2,:]=N[2,:]/np.max(np.abs(N[2,:4]))
                N[3,:]=N[3,:]/np.max(np.abs(N[3,:4]))
                add=True
                for t1 in range(0,4):
                    if((2*np.abs(N[t1,t1])<np.sum(np.abs(N[t1,:4])))|(2*np.abs(N[t1,t1])<np.sum(np.abs(N[:,t1])))):
                        add=False  
                if(add):
                    print(N)
                    print(i,j,k,n)
                    print(" ")
                    l.append((N,[i,j,k,n]))
print(len(l))                    

[[-1.         -0.08064516  0.04032258 -0.34946237 -0.46155914]
 [ 0.0875     -1.         -0.10416667  0.46666667  0.5075    ]
 [-0.65242718 -0.05242718 -1.         -0.03495146 -1.90582524]
 [ 0.04464286 -0.23214286  0.32142857 -1.          2.14553571]]
[-1, 0, 0, -1] [0, -1, 0, 1] [-1, 0, -1, 0] [0, 0, 0, -1]
 
[[-1.         -0.08064516  0.04032258 -0.34946237 -0.46155914]
 [ 0.0875     -1.         -0.10416667  0.46666667  0.5075    ]
 [-0.65242718 -0.05242718 -1.         -0.03495146 -1.90582524]
 [-0.04464286  0.23214286 -0.32142857  1.         -2.14553571]]
[-1, 0, 0, -1] [0, -1, 0, 1] [-1, 0, -1, 0] [0, 0, 0, 1]
 
[[-1.00000000e+00 -8.06451613e-02  4.03225806e-02 -3.49462366e-01
  -4.61559140e-01]
 [ 8.75000000e-02 -1.00000000e+00 -1.04166667e-01  4.66666667e-01
   5.07500000e-01]
 [-6.18874773e-01 -1.81488203e-03 -1.00000000e+00  1.70598911e-01
  -2.21742287e+00]
 [ 4.46428571e-02 -2.32142857e-01  3.21428571e-01 -1.00000000e+00
   2.14553571e+00]]
[-1, 0, 0, -1] [0, -1, 0, 1] [-1, 

In [37]:
min=np.sum(np.abs(l[0][1]))
minnum=0
num=0

for s in l:
    if(np.sum(np.abs(s[1]))<min):
        min=np.sum(np.abs(s[1]))
        minnum=num
    num+=1   

print(l[minnum],min)     

(array([[-1.        , -0.01061008, -0.05570292, -0.04774536, -1.0928382 ],
       [-0.09774436,  1.        , -0.04135338,  0.        , -1.3612782 ],
       [ 0.08299595, -0.0465587 , -1.        ,  0.        , -1.15283401],
       [ 0.04464286, -0.23214286,  0.32142857, -1.        ,  2.14553571]]), [[-1, 0, 0, 0], [0, 1, 0, 0], [0, 0, -1, 0], [0, 0, 0, -1]]) 4


In [ ]:
for n in l3:
    for k in l2:
        for j in l1:
            for i in l0:
                N=np.zeros_like(X,dtype='float64')
                for s in range(0,4):
                    N[0,:]=N[0,:]+X[s,:]*i[s]
                    N[1,:]=N[1,:]+X[s,:]*j[s]
                    N[2,:]=N[2,:]+X[s,:]*k[s]
                    N[3,:]=N[3,:]+X[s,:]*n[s]
                print(N)    
                add=True
                for t1 in range(0,4):
                    if((2*np.abs(N[t1,t1])<np.sum(np.abs(N[t1,:4])))|(2*np.abs(N[t1,t1])<np.sum(np.abs(N[:,t1])))):
                        add=False  
                if(add):
                    print(N)
                    print(i,j,k,n)
                    print(" ")
                    l.append((N,[i,j,k,n]))                    

In [ ]:
X=np.array([[ 100,  0.04,  0.21,  0.18,4.12],
 [ 2.74, -0.34, -0.11,  0., 3.279  ],
 [ 4.59,  0.23, -0.06,  0., 95  ],
 [ 0.95,  0.26, -0.36,  0.12, 0.097]],dtype='float64')
A=np.array(X*1000,dtype="int")
A

In [ ]:
import numpy as np
import pandas as pd

df = pd.DataFrame(np.nan, index=[0, 1, 2, 3], columns=['I', 'II', 'III'])
df.loc[0,"I"] = 1
df.loc[1,"I"] = 2
df.loc[2,"I"] = 3
df.loc[3,"I"] = 4
df.loc[0,"II"] = 5
df.loc[1,"II"] = 6
df.loc[2,"III"] = 7
df.loc[3,"III"] = 6
# далее запишите ваш код
df.set_axis(range(1,5),axis=0)
df.set_axis(['A','B','C'],axis=1)
df.fillna(55,inplace=True)
df

A     B     C
1  1.0   5.0  55.0
2  2.0   6.0  55.0
3  3.0  55.0   7.0
4  4.0  55.0   6.0

In [8]:
import pandas as pd
import numpy as np

fruit = np.array(["lemons", "lemons", "lemons", "lemons",
             	"apples", "apples", "apples", "apples",
             	"apples", "apples", "apples"],
            	dtype=object)

shop = np.array(["Shop A", "Shop A", "Shop A", "Shop B",
             	"Shop A", "Shop A", "Shop A", "Shop B",
             	"Shop B", "Shop B", "Shop A"],
            	dtype=object)
 
pl = np.array(["online", "online", "offline",
             	"online", "online", "offline",
             	"offline", "online", "offline",
             	"offline", "offline"],
            	dtype=object)

df = pd.DataFrame({'fruit': fruit, 'shop': shop, 'pl': pl,
               	"Q": [1, 2, 2, 3, 3, 4, 5, 6, 7, 4, 4],
               	"P": [5, 4, 5, 5, 6, 6, 8, 9, 9, 3, 3]})
df['total'] = df['Q']*df['P']
df

fruit    shop       pl  Q  P  total
0   lemons  Shop A   online  1  5      5
1   lemons  Shop A   online  2  4      8
2   lemons  Shop A  offline  2  5     10
3   lemons  Shop B   online  3  5     15
4   apples  Shop A   online  3  6     18
5   apples  Shop A  offline  4  6     24
6   apples  Shop A  offline  5  8     40
7   apples  Shop B   online  6  9     54
8   apples  Shop B  offline  7  9     63
9   apples  Shop B  offline  4  3     12
10  apples  Shop A  offline  4  3     12

In [26]:
subset=df.loc[(df.Q>3)&(df.shop=="Shop A")].reset_index()
total2=subset['total'][1]
fruit_total=df.groupby("fruit")["total"].sum()
fruit_quantity=df.groupby("fruit")["Q"].sum()
lemon_average_price=df.loc[df["fruit"]=="lemons"].groupby("fruit")["P"].mean()

In [27]:
subset
type(fruit_total)
fruit_quantity
lemon_average_price


fruit
lemons    4.75
Name: P, dtype: float64

In [28]:
import pandas as pd
import numpy as np

fruit = np.array(["lemons", "lemons", "lemons", "lemons",
                 "apples", "apples", "apples", "apples",
                 "apples", "apples", "apples"],
                dtype=object)

shop = np.array(["Shop A", "Shop A", "Shop A", "Shop B",
                 "Shop A", "Shop A", "Shop A", "Shop B",
                 "Shop B", "Shop B", "Shop A"],
                dtype=object)
  
pl = np.array(["online", "online", "offline",
                 "online", "online", "offline",
                 "offline", "online", "offline",
                 "offline", "offline"],
                dtype=object)



df = pd.DataFrame({'fruit': fruit, 'shop': shop, 'pl': pl,
                   "Q": [1, 2, 2, 3, 3, 4, 5, 6, 7, 4, 4],
                   "P": [5, 4, 5, 5, 6, 6, 8, 9, 9, 3,3]})
df['total'] = df['Q']*df['P']
# далее запишите ваш код

In [34]:
pivot=pd.pivot_table(df,values="total",index=["shop"],columns=["pl"],aggfunc='sum')
print(pivot.iloc[1,1])

69


In [33]:
pivot

pl      offline  online
shop                   
Shop A       86      31
Shop B       75      69